USE [111]
GO

/****** Object:  Table [dbo].[Items]    Script Date: 2018-10-23 16:23:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Items](
	[ID] [int] NOT NULL,
	[ItemCode] [varchar](30) NOT NULL,
	[Description] [varchar](60) NULL,
	[SecurityLevel] [int] NOT NULL,
	[Type] [char](1) NULL,
	[Assortment] [int] NOT NULL,
	[Class_01] [varchar](30) NULL,
	[Class_02] [varchar](30) NULL,
	[Class_03] [varchar](30) NULL,
	[Class_04] [varchar](30) NULL,
	[Class_05] [varchar](30) NULL,
	[Class_06] [varchar](30) NULL,
	[Class_07] [varchar](30) NULL,
	[Class_08] [varchar](30) NULL,
	[Class_09] [varchar](30) NULL,
	[Class_10] [varchar](30) NULL,
	[IsSalesItem] [bit] NOT NULL,
	[IsPurchaseItem] [bit] NOT NULL,
	[IsServiceItem] [bit] NOT NULL,
	[IsTextItem] [bit] NOT NULL,
	[IsStockItem] [bit] NOT NULL,
	[IsSerialNumberItem] [bit] NOT NULL,
	[IsSubAssemblyItem] [bit] NOT NULL,
	[IsPriceRegulationItem] [bit] NOT NULL,
	[IsBackOrderItem] [bit] NOT NULL,
	[IsFractionAllowedItem] [bit] NOT NULL,
	[IsPrintItem] [bit] NOT NULL,
	[EANCode] [varchar](30) NULL,
	[BARCode] [varchar](60) NULL,
	[BARCodeType] [varchar](30) NULL,
	[StockCurrency] [varchar](3) NULL,
	[StockValuationType] [int] NULL,
	[StockValuationDate] [datetime] NULL,
	[WareHouse] [varchar](4) NULL,
	[WareHouseLocation] [varchar](30) NULL,
	[CostPriceCurrency] [varchar](3) NULL,
	[CostPriceCalculated] [float] NOT NULL,
	[CostPriceCalculatedManually] [float] NOT NULL,
	[CostPriceStandard] [float] NOT NULL,
	[PurchaseCurrency] [char](3) NULL,
	[PurchasePrice] [float] NOT NULL,
	[PurchaseVATPerc] [float] NOT NULL,
	[PurchaseVATIncl] [bit] NOT NULL,
	[SalesPriceType] [int] NOT NULL,
	[DimensionsInText] [varchar](60) NULL,
	[WeightInText] [varchar](60) NULL,
	[Picture] [image] NULL,
	[PictureFilename] [varchar](128) NULL,
	[UserField_01] [varchar](255) NULL,
	[UserField_02] [varchar](255) NULL,
	[UserField_03] [varchar](255) NULL,
	[UserField_04] [varchar](255) NULL,
	[UserField_05] [varchar](255) NULL,
	[UserField_06] [varchar](255) NULL,
	[UserField_07] [varchar](255) NULL,
	[UserField_08] [varchar](255) NULL,
	[UserField_09] [varchar](255) NULL,
	[UserField_10] [varchar](255) NULL,
	[UserDate_01] [datetime] NULL,
	[UserDate_02] [datetime] NULL,
	[UserDate_03] [datetime] NULL,
	[UserDate_04] [datetime] NULL,
	[UserDate_05] [datetime] NULL,
	[UserNumber_01] [float] NULL,
	[UserNumber_02] [float] NULL,
	[UserNumber_03] [float] NULL,
	[UserNumber_04] [float] NULL,
	[UserNumber_05] [float] NULL,
	[UserYesNo_01] [bit] NOT NULL,
	[UserYesNo_02] [bit] NOT NULL,
	[UserYesNo_03] [bit] NOT NULL,
	[UserYesNo_04] [bit] NOT NULL,
	[UserYesNo_05] [bit] NOT NULL,
	[RegulationType] [int] NOT NULL,
	[RegulationFixedAmount] [float] NOT NULL,
	[RegulationAmount] [float] NOT NULL,
	[RegulationCurrency] [varchar](3) NULL,
	[RegulationPercentage] [float] NOT NULL,
	[RegulationItemsIncluded] [varchar](255) NULL,
	[RegulationItemsExcluded] [varchar](255) NULL,
	[RegulationPriority] [int] NOT NULL,
	[ItemCodeReplacement] [varchar](30) NULL,
	[ItemType] [char](1) NULL,
	[IsAssembled] [tinyint] NOT NULL,
	[SearchCode] [char](13) NULL,
	[eenh_verk] [char](5) NULL,
	[aant_verp] [float] NULL,
	[SalesPackagePrice] [float] NULL,
	[PurchaseOrderAdviceCode] [char](1) NULL,
	[SalesVatCode] [char](3) NULL,
	[PurchaseVatCode] [char](3) NULL,
	[StatisticalNumber] [char](9) NULL,
	[PackageDescription] [char](8) NULL,
	[SerialBatchItem] [char](1) NULL,
	[IsBatchItem] [tinyint] NOT NULL,
	[IsBackToBackOrder] [tinyint] NOT NULL,
	[UserNumber_06] [float] NULL,
	[UserNumber_07] [float] NULL,
	[UserNumber_08] [float] NULL,
	[PurchaseFactor] [char](3) NULL,
	[SalesFactor] [char](3) NULL,
	[StatisticalUnits] [float] NULL,
	[NetWeight] [float] NULL,
	[GrossWeight] [float] NULL,
	[ExtraDutyVATcode] [char](3) NULL,
	[SalesMarginPercent] [float] NULL,
	[status] [char](1) NULL,
	[Condition] [char](1) NULL,
	[IsDiscount] [tinyint] NOT NULL,
	[IsExplode] [tinyint] NOT NULL,
	[IsCentralItem] [tinyint] NOT NULL,
	[lev_crdnr] [char](6) NULL,
	[Percentage_1] [float] NOT NULL,
	[Percentage_2] [float] NOT NULL,
	[Description_0] [varchar](60) NULL,
	[Description_1] [varchar](60) NULL,
	[Description_2] [varchar](60) NULL,
	[Description_3] [varchar](60) NULL,
	[Description_4] [varchar](60) NULL,
	[LongDescription] [varchar](160) NULL,
	[TextDescription] [text] NULL,
	[GLAccountRevenue] [varchar](9) NULL,
	[GLAccountCost] [varchar](9) NULL,
	[GLAccountDistribution] [varchar](9) NULL,
	[GLAccountAsset] [varchar](9) NULL,
	[LevelCode] [int] NOT NULL,
	[CountingCycle] [smallint] NOT NULL,
	[RequiresApprovedSupplier] [tinyint] NOT NULL,
	[OrderPolicyCode] [char](1) NULL,
	[PeriodOrderDays] [int] NOT NULL,
	[StatisticalFactorSales] [float] NULL,
	[StatisticalFactorPurchase] [float] NULL,
	[TaxItemClassification] [int] NOT NULL,
	[UserNumber_09] [float] NULL,
	[UserNumber_10] [float] NULL,
	[UserNumber_11] [float] NULL,
	[UserNumber_12] [float] NULL,
	[UserNumber_13] [float] NULL,
	[ConfigurationClass] [varchar](30) NULL,
	[ConfigurationModel] [text] NULL,
	[ValuationMethod] [char](1) NULL,
	[Shelflife] [int] NOT NULL,
	[Warranty] [int] NOT NULL,
	[IsOutsideProcess] [bit] NULL,
	[GLAccountStkCoverage] [char](9) NULL,
	[GLAccountStkChange] [char](9) NULL,
	[ItemToBeReceivedLedger] [char](9) NULL,
	[IntrastatEnabled] [bit] NOT NULL,
	[AddExtraReceiptToOrder] [bit] NOT NULL,
	[IsOutsourcedItem] [bit] NOT NULL,
	[GLAccountDiscount] [char](9) NULL,
	[LinkItemCode] [varchar](30) NULL,
	[IsTaxItem] [tinyint] NOT NULL,
	[Division] [smallint] NULL,
	[syscreated] [datetime] NOT NULL,
	[syscreator] [int] NOT NULL,
	[sysmodified] [datetime] NOT NULL,
	[sysmodifier] [int] NOT NULL,
	[sysguid] [uniqueidentifier] NOT NULL,
	[timestamp] [timestamp] NOT NULL,
	[CSPickITScanCode] [varchar](30) NULL,
	[CSPickITCWItemCode] [varchar](30) NULL,
	[SerialBatchMask] [varchar](30) NULL,
	[IncrementFactor] [int] NULL,
	[IsCommissionable] [bit] NULL,
	[CommissionMethod] [char](1) NOT NULL,
	[CommissionValue] [float] NULL,
	[HTSCode] [varchar](14) NULL,
	[GTIN] [varchar](20) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


